# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nathan/dev/mine/SudokuSolver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nathan/dev/mine/SudokuSolver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/dev/mine/SudokuSolver/CMakeFiles /home/nathan/dev/mine/SudokuSolver//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nathan/dev/mine/SudokuSolver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sudokuSolver

# Build rule for target.
sudokuSolver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sudokuSolver
.PHONY : sudokuSolver

# fast build rule for target.
sudokuSolver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/build
.PHONY : sudokuSolver/fast

Techniques/baseTechniques.o: Techniques/baseTechniques.cpp.o
.PHONY : Techniques/baseTechniques.o

# target to build an object file
Techniques/baseTechniques.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Techniques/baseTechniques.cpp.o
.PHONY : Techniques/baseTechniques.cpp.o

Techniques/baseTechniques.i: Techniques/baseTechniques.cpp.i
.PHONY : Techniques/baseTechniques.i

# target to preprocess a source file
Techniques/baseTechniques.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Techniques/baseTechniques.cpp.i
.PHONY : Techniques/baseTechniques.cpp.i

Techniques/baseTechniques.s: Techniques/baseTechniques.cpp.s
.PHONY : Techniques/baseTechniques.s

# target to generate assembly for a file
Techniques/baseTechniques.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Techniques/baseTechniques.cpp.s
.PHONY : Techniques/baseTechniques.cpp.s

Techniques/singleNaked.o: Techniques/singleNaked.cpp.o
.PHONY : Techniques/singleNaked.o

# target to build an object file
Techniques/singleNaked.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Techniques/singleNaked.cpp.o
.PHONY : Techniques/singleNaked.cpp.o

Techniques/singleNaked.i: Techniques/singleNaked.cpp.i
.PHONY : Techniques/singleNaked.i

# target to preprocess a source file
Techniques/singleNaked.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Techniques/singleNaked.cpp.i
.PHONY : Techniques/singleNaked.cpp.i

Techniques/singleNaked.s: Techniques/singleNaked.cpp.s
.PHONY : Techniques/singleNaked.s

# target to generate assembly for a file
Techniques/singleNaked.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Techniques/singleNaked.cpp.s
.PHONY : Techniques/singleNaked.cpp.s

Tools/tools.o: Tools/tools.cpp.o
.PHONY : Tools/tools.o

# target to build an object file
Tools/tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Tools/tools.cpp.o
.PHONY : Tools/tools.cpp.o

Tools/tools.i: Tools/tools.cpp.i
.PHONY : Tools/tools.i

# target to preprocess a source file
Tools/tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Tools/tools.cpp.i
.PHONY : Tools/tools.cpp.i

Tools/tools.s: Tools/tools.cpp.s
.PHONY : Tools/tools.s

# target to generate assembly for a file
Tools/tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Tools/tools.cpp.s
.PHONY : Tools/tools.cpp.s

Tools/verifMethods.o: Tools/verifMethods.cpp.o
.PHONY : Tools/verifMethods.o

# target to build an object file
Tools/verifMethods.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Tools/verifMethods.cpp.o
.PHONY : Tools/verifMethods.cpp.o

Tools/verifMethods.i: Tools/verifMethods.cpp.i
.PHONY : Tools/verifMethods.i

# target to preprocess a source file
Tools/verifMethods.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Tools/verifMethods.cpp.i
.PHONY : Tools/verifMethods.cpp.i

Tools/verifMethods.s: Tools/verifMethods.cpp.s
.PHONY : Tools/verifMethods.s

# target to generate assembly for a file
Tools/verifMethods.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/Tools/verifMethods.cpp.s
.PHONY : Tools/verifMethods.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/main.cpp.s
.PHONY : main.cpp.s

solver.o: solver.cpp.o
.PHONY : solver.o

# target to build an object file
solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/solver.cpp.o
.PHONY : solver.cpp.o

solver.i: solver.cpp.i
.PHONY : solver.i

# target to preprocess a source file
solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/solver.cpp.i
.PHONY : solver.cpp.i

solver.s: solver.cpp.s
.PHONY : solver.s

# target to generate assembly for a file
solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sudokuSolver.dir/build.make CMakeFiles/sudokuSolver.dir/solver.cpp.s
.PHONY : solver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sudokuSolver"
	@echo "... Techniques/baseTechniques.o"
	@echo "... Techniques/baseTechniques.i"
	@echo "... Techniques/baseTechniques.s"
	@echo "... Techniques/singleNaked.o"
	@echo "... Techniques/singleNaked.i"
	@echo "... Techniques/singleNaked.s"
	@echo "... Tools/tools.o"
	@echo "... Tools/tools.i"
	@echo "... Tools/tools.s"
	@echo "... Tools/verifMethods.o"
	@echo "... Tools/verifMethods.i"
	@echo "... Tools/verifMethods.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... solver.o"
	@echo "... solver.i"
	@echo "... solver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

