name: Deploy Nuxt App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3
       
         
      - name: Build and run Docker container
        run: |
        
          docker build -t sudoku-front ./front
          docker stop sudoku-front || true
          docker rm sudoku-front || true
          docker run -d --name sudoku-front -p 3002:3002 sudoku-front

      
