name: Deploy Nuxt App with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v3
       
      - name: Build and run Docker front
        run: |
        
          docker build -t sudoku-front ./front
          docker stop sudoku-front || true
          docker rm sudoku-front || true
          docker run -d --name sudoku-front -p 3003:3003 sudoku-front

      - name: Build and run Docker api
        run: |
        
          docker build -t sudoku-api ./back
          docker stop sudoku-api || true
          docker rm sudoku-api || true
          docker run -d --name sudoku-api -p 3004:3004 sudoku-api

